### PR TITLE
Btag v2

### PR DESCRIPTION
**Pull request by andrzejnovak**
- Add BTV variables for jet/fatjet/subjet
- Add SV jet constituents

### CODE REVIEW

**Comment by alefisico** [comment]
For reference:
 * Content: http://algomez.web.cern.ch/algomez/testWeb/JMARnanoplusBTag_content_v01.html
 * Size: http://algomez.web.cern.ch/algomez/testWeb/JMARnanoplusBTag_size_v01.html

**Comment by andrzejnovak** [comment]
@alefisico cool, it looks like adding SV info is fairly cheap storage-wise

**Comment by alefisico** [comment]
I dont have any major comment about this. If @rappoccio @laurenhay also dont have major comment, we can merge it to the master.

**Comment by andrzejnovak** [comment]
@rappoccio I've marked some of the SV variables if they are jet related or independent. I am not sure I understood exactly how you went about splitting the variables for PF cands, but if you have a moment later to do that splitting for the SVs as well that would be great. Even though this doesn't take up that much space.

**Comment by rappoccio** [comment]
@andrzejnovak The information for PFCandidates is all per-candidate [here](https://github.com/cms-jet/NanoAODJMAR/blob/253b4c0852a3e87df4e61a6b5a6b3083952230e4/python/addPFCands_cff.py#L28). There is additional information about track-->jet association [here](https://github.com/cms-jet/NanoAODJMAR/blob/253b4c0852a3e87df4e61a6b5a6b3083952230e4/python/addPFCands_cff.py#L49). Although, I'm not quite sure if that's what you mean.

**Comment by andrzejnovak** [comment]
@rappoccio Oh I think I finally understand. You create two separate tables for PF related info and add the cand index to link them, is that correct?

**Comment by rappoccio** [comment]
There's one table for PF candidates, and one table for variables that depend on both PF candidates AND the jet.

**Pull request merged**
