### PR TITLE
Naming proposal for PF cand collections

### PR DESCRIPTION
**Pull request by andrzejnovak**
Baseline: `PFCands`
- Related to AK4 Jet info - `JetPFCands (extending `Jet` collection)
- Related to AK8 Jet info - `FatJetPFCands (extending `FatJet` collection)

pinging @laurenhay @nsmith- @alefisico

### CODE REVIEW

**Comment by alefisico** [comment]
I'm getting this error with this PR:
```
----- Begin Fatal Exception 05-Nov-2020 14:07:05 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Validating configuration of module: class=PatJetConstituentTableProducer label='customAK4ConstituentsTable'
Exception Message:
Illegal parameters found in configuration.  The parameters are named:
 'idx_name'
 'idx_nameSV'
You could be trying to use parameter names that are not
allowed for this plugin or they could be misspelled.
----- End Fatal Exception -------------------------------------------------
```

**Comment by andrzejnovak** [comment]
Let me check, but I've opened this for now mostly for discussion on the naming first.

**Comment by andrzejnovak** [comment]
@alefisico is it possible you didn't rebuild? It runs for me and the parameters seem to be part of the PR

**Comment by alefisico** [comment]
> @alefisico is it possible you didn't rebuild? It runs for me and the parameters seem to be part of the PR

ups yes you are right, sorry for the noise :smile:

**Comment by andrzejnovak** [comment]
@alefisico I would say we can merge this since there don't seem to be any other comments

**Pull request merged**
